<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_25</name>
   <tag></tag>
   <elementGuidId>61b1ab26-3f4c-4168-8dab-d001e6cc0ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;25€&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d8c5750-9bfb-47f7-bc46-ea459fe44a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b43f45e-c8ab-482c-8f66-fad0598c97e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active:bg-neutral md:w-52 w-24 h-10 p-2 rounded-xl flex justify-center items-center bg-primary</value>
      <webElementGuid>cdc71b8a-0ff6-4ffd-8b17-3589b6144def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25€</value>
      <webElementGuid>a31eaa5c-8be2-4bfa-b86b-509b6baf58df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:r6:&quot;)/form[1]/div[@class=&quot;w-full border border-zinc-400 rounded-xl h-fit flex flex-col md:flex-row justify-start px-2 py-1 gap-2&quot;]/div[@class=&quot;flex justify-around gap-1 items-center overflow-hidden&quot;]/button[@class=&quot;active:bg-neutral md:w-52 w-24 h-10 p-2 rounded-xl flex justify-center items-center bg-primary&quot;]</value>
      <webElementGuid>431c5372-234b-4d3e-889f-62773487cad7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>1a5de2ed-da14-4574-8f9d-7004a1de96c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r6:']/form/div/div/button</value>
      <webElementGuid>7c71f0ac-04d0-44b4-bffa-191106441a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='offrir une activité'])[1]/following::button[1]</value>
      <webElementGuid>ba33ada1-208d-4cae-a019-b8729a5975d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offrir une carte cadeau'])[2]/following::button[2]</value>
      <webElementGuid>0633f615-0012-4b86-9a1f-cf2718926684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envoyer une carte cadeau à un ou une ami(e) ?'])[1]/preceding::button[7]</value>
      <webElementGuid>9097f413-fcc3-4ddd-b03c-54aa535f38c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suivant'])[1]/preceding::button[7]</value>
      <webElementGuid>4eb37680-2370-4b14-a245-928f95bcdaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/button</value>
      <webElementGuid>913c9bea-737d-4f3a-8dbc-3c4c42289cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '25€' or . = '25€')]</value>
      <webElementGuid>c90fb5e9-86e0-42e3-ac51-88a40ce92f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
