<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Suivant</name>
   <tag></tag>
   <elementGuidId>ef6abaa5-c370-4419-9e2d-721bd339290f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Suivant&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70691aa4-c0a5-4dc1-8779-093131d3aa7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>81749633-8c55-46cb-8de1-c6a42e0488e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-11 rounded-xl p-2.5 float-right border border-black font-sans font-medium sm:text-base text-xs opacity-100 bg-primary text-accent</value>
      <webElementGuid>6db8dbad-7a38-4467-b37b-ace7e2fbe082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suivant</value>
      <webElementGuid>76549138-f528-47e5-a3cb-09f00a49f655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:r1g:&quot;)/form[1]/div[@class=&quot;flex flex-col gap-2 justify-center items-center&quot;]/button[@class=&quot;w-full h-11 rounded-xl p-2.5 float-right border border-black font-sans font-medium sm:text-base text-xs opacity-100 bg-primary text-accent&quot;]</value>
      <webElementGuid>43926791-08a8-4f72-a787-38edbe3b2cc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>1892dc40-8616-455c-8879-afe419404298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r1g:']/form/div[4]/button</value>
      <webElementGuid>aeccd8c5-fe61-4dbe-a962-d669fdfa04d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envoyer une carte cadeau à un ou une ami(e) ?'])[1]/following::button[1]</value>
      <webElementGuid>3e3ed735-c9af-414e-a388-f60a25ea1100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='offrir une activité'])[1]/following::button[8]</value>
      <webElementGuid>9a2ef09d-02dd-4a1c-bafe-2903f61a3241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuer mes achats'])[1]/preceding::button[1]</value>
      <webElementGuid>bc29f922-861c-459b-af74-d9f606e4649b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suivant']/parent::*</value>
      <webElementGuid>197e7182-407f-4fc0-9662-3b120227ee8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>842488f4-b06e-43ae-b90f-98890e8bdb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Suivant' or . = 'Suivant')]</value>
      <webElementGuid>ce954025-f371-4e8b-86eb-ebd2601e9e94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
