<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_250CHF</name>
   <tag></tag>
   <elementGuidId>1305eb08-6cc1-4f6b-8e87-4c39e4bdb2ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;250CHF&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9aa8c475-edce-41d3-be1e-8bb0578ade6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>126623ef-70d5-4d2c-8409-19cb4e2dbbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active:bg-neutral md:w-52 w-24 h-10 p-2 rounded-xl flex justify-center items-center bg-primary</value>
      <webElementGuid>2ca513d3-5d04-42fd-bd13-efed9a85f574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>250CHF</value>
      <webElementGuid>95aff8e2-2732-4a29-917c-76809e124de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-panel-:r1g:&quot;)/form[1]/div[@class=&quot;w-full border border-zinc-400 rounded-xl h-fit flex flex-col md:flex-row justify-start px-2 py-1 gap-2&quot;]/div[@class=&quot;flex justify-around gap-1 items-center overflow-hidden&quot;]/button[@class=&quot;active:bg-neutral md:w-52 w-24 h-10 p-2 rounded-xl flex justify-center items-center bg-primary&quot;]</value>
      <webElementGuid>6f2390b9-6d68-4e3d-8c57-3ef1621f38ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>235ec5c0-4adc-4f98-a983-63315c1c49d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-tabs-panel-:r1g:']/form/div/div/button[5]</value>
      <webElementGuid>c15306c0-8537-46c5-bf50-912792d622c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='offrir une activité'])[1]/following::button[5]</value>
      <webElementGuid>6e5a51cc-c10b-4b6b-a84b-5059bb5d34cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offrir une carte cadeau'])[2]/following::button[6]</value>
      <webElementGuid>76d9b929-0bf9-4fca-a149-084fbcf8f75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envoyer une carte cadeau à un ou une ami(e) ?'])[1]/preceding::button[3]</value>
      <webElementGuid>f001b04e-504b-4c10-a2c0-df3458c74d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suivant'])[1]/preceding::button[3]</value>
      <webElementGuid>f18b918d-8ce0-4a36-a43f-4319a18bf71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>d3cd5be4-5de6-448f-922b-e78e2d250a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '250CHF' or . = '250CHF')]</value>
      <webElementGuid>0c96500c-1269-4dc3-b855-1632d96b2b0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
