<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25</name>
   <tag></tag>
   <elementGuidId>af84f5a9-b056-4bbd-b0e2-636b15435e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.rounded-xl.bg-primary:nth-child(1) span.font-sans</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-xl ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-primary ') and (position() = 1)]//span[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-sans ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa3f5c06-e35b-4472-bc26-368ccdc8ff49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-sans text-white</value>
      <webElementGuid>b76025e6-edde-4113-9db0-c0fcb0a2bc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25€</value>
      <webElementGuid>001a7857-0c99-48af-bcc3-571d7fca03be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-140235f04c540888156ee2473caa3a7f</value>
      <webElementGuid>18bdf363-b00a-483b-a17f-b78efd90cbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-xl ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-primary ') and (position() = 1)]//span[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-sans ')]</value>
      <webElementGuid>5e654a86-8c0d-4759-96d1-d4af8a90adbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-xl ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-primary ') and (position() = 1)]//span[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-sans ')]</value>
      <webElementGuid>3b1c8da5-cd74-4bf5-b76b-daf811698aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '25€' or . = '25€')]</value>
      <webElementGuid>069d51a2-5678-43be-872c-da81dfd9fb35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
