<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_200</name>
   <tag></tag>
   <elementGuidId>317ac5ff-fb40-4535-91bd-032e19460680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.rounded-xl.bg-primary:nth-child(4) span.font-sans.text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-xl ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-primary ') and (position() = 4)]//span[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-sans ') and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1ebff47-d0a0-49e0-92cf-950918f5c6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-sans text-white</value>
      <webElementGuid>ea16ee9b-87e8-4b28-8171-5f4edf0c4211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>200€</value>
      <webElementGuid>b91cb883-b80e-460f-bc2f-d5c9a02e9542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b0641b257d1d3ef87381cd28426a72cd</value>
      <webElementGuid>435545f7-35cb-44db-999b-d666a33dd94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-xl ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-primary ') and (position() = 4)]//span[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-sans ') and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      <webElementGuid>4f901ee1-ec9a-433d-b498-d8f3fcdc01fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-xl ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-primary ') and (position() = 4)]//span[@class and contains(concat(' ', normalize-space(@class), ' '), ' font-sans ') and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      <webElementGuid>056e3cd0-d16f-4a98-87ba-20024cc6e7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '200€' or . = '200€')]</value>
      <webElementGuid>864b9742-5907-4297-a0e4-95a173b9071c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
