<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__2</name>
   <tag></tag>
   <elementGuidId>290f044b-de92-466c-ad5a-ff816df55f05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Entrez le prénom&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4df17ec7-fbd2-4dc5-950b-22bf93f07cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-12 my-2 mb-4 w-full px-4 py-3 text-base text-black leading-[18px] font-normal border border-solid border-[var(--neutral-gray)] placeholder-[var(--neutral-gray)] focus:outline-none rounded-[18px] bg-[#FCFBFF]</value>
      <webElementGuid>557aebc1-9fc4-4cff-a8f3-60b2f3053e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Entrez le prénom</value>
      <webElementGuid>98f30116-e069-4dc6-9a95-caec0ddd0c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ae334eed-dd69-4ea3-b770-77268a8d5c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-testing</value>
      <webElementGuid>c24f05d7-66bc-4fde-a52c-e9acbc51520e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33f3fb2e-dfd2-453c-8727-783f34182d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9119ea00-6570-4b65-8bc3-18b0ffc98cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>305ff73a-be17-4a4f-9f0a-2c8495887c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_6dfd4a __variable_f8227e notranslate&quot;]/body[1]/div[1]/main[@class=&quot;mt-8 mb-10 md:mx-[6.75%] mx-6&quot;]/section[@class=&quot;lg:mt-5 sm:mt-4 mt-6 lg:mb-16 sm:mb-10 mb-8 mx-4&quot;]/div[@class=&quot;flex justify-center mb-8&quot;]/div[@class=&quot;w-full rounded-[1.125rem] bg-[#FCFBFF] lg:p-7 p-2 shadow-[0_0_1.5rem_-0.25rem_#00000029]&quot;]/div[@class=&quot;grid sm:grid-cols-2 sm:justify-between justify-center sm:gap-6 gap-4 items-center sm:items-start&quot;]/div[2]/div[@class=&quot;py-2&quot;]/div[@class=&quot;relative flex&quot;]/input[@class=&quot;h-12 my-2 mb-4 w-full px-4 py-3 text-base text-black leading-[18px] font-normal border border-solid border-[var(--neutral-gray)] placeholder-[var(--neutral-gray)] focus:outline-none rounded-[18px] bg-[#FCFBFF]&quot;]</value>
      <webElementGuid>508d4e15-fb3a-449b-804d-a993b402a1c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='2']</value>
      <webElementGuid>f33ccdc0-7f59-4053-b866-25054dc45b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>dbc49d7a-68bd-4016-ae0d-7044fd27e452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Entrez le prénom' and @type = 'textarea' and @name = '2']</value>
      <webElementGuid>a840448c-50ff-49e8-8e29-93a96f5637bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
