<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__3</name>
   <tag></tag>
   <elementGuidId>6ad355a6-519d-4cad-a5cd-dc3111f017f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Entrez le téléphone&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd3e26c8-7eb2-4a05-be3e-d8d03c5226ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-12 my-2 py-2 w-full px-4 py-3 text-base text-black leading-[18px] font-normal border border-solid border-[var(--neutral-gray)] placeholder-[var(--neutral-gray)] focus:outline-none rounded-[18px] bg-[#FCFBFF]</value>
      <webElementGuid>b6cf2f4e-277d-4003-a88c-b989b5a9b460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Entrez le téléphone</value>
      <webElementGuid>f60787c8-e49f-4dff-a7f1-efa1f914dd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c2033dc5-1371-409f-81ea-624d44866e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-testing</value>
      <webElementGuid>62988c02-869c-41d9-a021-598974f6a5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ca306c3e-7d72-43af-86c2-6de2a6c76581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>bbb7fd3b-28e2-4d34-8037-e426a192cbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7cbb885f-1793-4751-b332-1b84243654ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_6dfd4a __variable_f8227e notranslate&quot;]/body[1]/div[1]/main[@class=&quot;mt-8 mb-10 md:mx-[6.75%] mx-6&quot;]/section[@class=&quot;lg:mt-5 sm:mt-4 mt-6 lg:mb-16 sm:mb-10 mb-8 mx-4&quot;]/div[@class=&quot;flex justify-center mb-8&quot;]/div[@class=&quot;w-full rounded-[1.125rem] bg-[#FCFBFF] lg:p-7 p-2 shadow-[0_0_1.5rem_-0.25rem_#00000029]&quot;]/div[@class=&quot;grid sm:grid-cols-2 sm:justify-between justify-center sm:gap-6 gap-4 items-center sm:items-start&quot;]/div[3]/div[@class=&quot;py-2&quot;]/div[@class=&quot;relative flex&quot;]/input[@class=&quot;h-12 my-2 py-2 w-full px-4 py-3 text-base text-black leading-[18px] font-normal border border-solid border-[var(--neutral-gray)] placeholder-[var(--neutral-gray)] focus:outline-none rounded-[18px] bg-[#FCFBFF]&quot;]</value>
      <webElementGuid>1c19e282-77c3-4d1a-bae1-047f077b90b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='3']</value>
      <webElementGuid>6f058cb9-be13-439f-86e2-01164c864593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>5ac4811c-5848-4691-803f-c16a852a6057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Entrez le téléphone' and @type = 'number' and @name = '3']</value>
      <webElementGuid>f65e2501-82cf-4b91-a410-a6ea7c1a7735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
