<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__1</name>
   <tag></tag>
   <elementGuidId>03ce2b76-c63e-45ea-8d4f-20b4ef1b7fe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Entrez le nom&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15adf608-9de5-4050-9607-f3c516d4490c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-12 my-2 mb-4 w-full px-4 py-3 text-base text-black leading-[18px] font-normal border border-solid border-[var(--neutral-gray)] placeholder-[var(--neutral-gray)] focus:outline-none rounded-[18px] bg-[#FCFBFF]</value>
      <webElementGuid>95f24e4d-acdf-4936-a5cb-75dedb3ecd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Entrez le nom</value>
      <webElementGuid>5bd95067-7e26-4086-8720-77ed2dff2925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0ad3add3-e032-4703-a135-8fb4de4308d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-testing</value>
      <webElementGuid>37e4ce9b-9a8f-4ea2-9bb1-75bf36d09ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4920765d-2052-4f0b-b157-0efe6d594776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a3a1a7b4-a8cd-4c19-8a17-4bf770338edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6b44cde2-25a5-43d7-873f-7de97f15b1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_6dfd4a __variable_f8227e notranslate&quot;]/body[1]/div[1]/main[@class=&quot;mt-8 mb-10 md:mx-[6.75%] mx-6&quot;]/section[@class=&quot;lg:mt-5 sm:mt-4 mt-6 lg:mb-16 sm:mb-10 mb-8 mx-4&quot;]/div[@class=&quot;flex justify-center mb-8&quot;]/div[@class=&quot;w-full rounded-[1.125rem] bg-[#FCFBFF] lg:p-7 p-2 shadow-[0_0_1.5rem_-0.25rem_#00000029]&quot;]/div[@class=&quot;grid sm:grid-cols-2 sm:justify-between justify-center sm:gap-6 gap-4 items-center sm:items-start&quot;]/div[1]/div[@class=&quot;py-2&quot;]/div[@class=&quot;relative flex&quot;]/input[@class=&quot;h-12 my-2 mb-4 w-full px-4 py-3 text-base text-black leading-[18px] font-normal border border-solid border-[var(--neutral-gray)] placeholder-[var(--neutral-gray)] focus:outline-none rounded-[18px] bg-[#FCFBFF]&quot;]</value>
      <webElementGuid>a45169f6-0d1e-43e8-aae8-0fdc4f16ab2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='1']</value>
      <webElementGuid>d694db9a-a78f-4623-a50a-4418364fe37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>98cdce08-090a-4383-b573-fcaccce8d2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Entrez le nom' and @type = 'textarea' and @name = '1']</value>
      <webElementGuid>b0ff36d3-4cc7-48dc-a7c9-6fc9f6edd886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
