<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__4</name>
   <tag></tag>
   <elementGuidId>4cb9a236-33b4-4691-ad85-fff5a9265960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Entrez le e-mail&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07a6ceb2-55c7-4c4a-9c87-fc37396174fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-12 my-2 mb-4 w-full px-4 py-3 text-base text-black leading-[18px] font-normal border border-solid border-[var(--neutral-gray)] placeholder-[var(--neutral-gray)] focus:outline-none rounded-[18px] bg-[#FCFBFF]</value>
      <webElementGuid>0ffaaac4-764b-470c-8f78-641c00143b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Entrez le e-mail</value>
      <webElementGuid>a6e07d2f-80e1-4e6e-bf3f-469f63e308f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>268b583c-e97b-4e78-a7d9-4d6c6deb9c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-testing</value>
      <webElementGuid>7517e518-27d0-4255-b9d1-a4c87a643619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d8de50e5-ffb2-4acf-8a2e-f0d2ea17c4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>87b55c01-0982-4aac-9fb6-9b6c3717c11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d7f30ac2-163c-4280-ad20-6c429762bd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_6dfd4a __variable_f8227e notranslate&quot;]/body[1]/div[1]/main[@class=&quot;mt-8 mb-10 md:mx-[6.75%] mx-6&quot;]/section[@class=&quot;lg:mt-5 sm:mt-4 mt-6 lg:mb-16 sm:mb-10 mb-8 mx-4&quot;]/div[@class=&quot;flex justify-center mb-8&quot;]/div[@class=&quot;w-full rounded-[1.125rem] bg-[#FCFBFF] lg:p-7 p-2 shadow-[0_0_1.5rem_-0.25rem_#00000029]&quot;]/div[@class=&quot;grid sm:grid-cols-2 sm:justify-between justify-center sm:gap-6 gap-4 items-center sm:items-start&quot;]/div[4]/div[@class=&quot;py-2&quot;]/div[@class=&quot;relative flex&quot;]/input[@class=&quot;h-12 my-2 mb-4 w-full px-4 py-3 text-base text-black leading-[18px] font-normal border border-solid border-[var(--neutral-gray)] placeholder-[var(--neutral-gray)] focus:outline-none rounded-[18px] bg-[#FCFBFF]&quot;]</value>
      <webElementGuid>9b529a5e-f82a-42a6-8df7-9a876dcaab67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='4']</value>
      <webElementGuid>25b8f762-c283-4b4d-8bd7-12129e06a8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>a7c6cc3c-19e0-49a9-b9a0-9ba090f4f6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Entrez le e-mail' and @type = 'email' and @name = '4']</value>
      <webElementGuid>2c75d26a-01d4-407c-b546-94d54b04358b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
