<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_headlessui-menu-item-_r8</name>
   <tag></tag>
   <elementGuidId>b2781d75-11ce-4f37-a20e-fc84a7a5d6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/discover\/food&quot;][role=&quot;menuitem&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@href = '/discover/food') and (@role = 'menuitem')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>108bbf26-7a9d-4729-a574-17979fac9765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/discover/food</value>
      <webElementGuid>945d1ea8-6c22-4956-a858-f2b1ee6be84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white w-full group flex items-center px-4 py-2 text-sm</value>
      <webElementGuid>bf4844eb-6f61-49cc-b24d-5c662b532b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-:r8:</value>
      <webElementGuid>3fe17b3e-d655-4776-9a53-bd0a67218903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>e11590e0-71a8-4457-8c45-a849eef2ab33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b0bb9135-c3e6-46f3-ba72-4118f0771f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Restaurant</value>
      <webElementGuid>ec756103-de10-4669-bf5e-8bcabcbec167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-947af593df4cf9a5c33af4dc3f6caa3d</value>
      <webElementGuid>751aacd8-f110-4ac1-a540-0ae83a535456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@href = '/discover/food') and (@role = 'menuitem')]</value>
      <webElementGuid>61c79f3a-6a10-4be9-92d0-29cb53008bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@href = '/discover/food') and (@role = 'menuitem')]</value>
      <webElementGuid>bf09c464-f938-4738-b37e-f74cdd9242a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/discover/food' and @id = 'headlessui-menu-item-:r8:' and (text() = 'Restaurant' or . = 'Restaurant')]</value>
      <webElementGuid>5d8de00c-7949-4aa7-b6ef-2d5589f9ce79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
