<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_headlessui-menu-item-_r7</name>
   <tag></tag>
   <elementGuidId>aea35f3c-e3c0-4c7b-83df-a049b970c9b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/discover\/serie&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/discover/serie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f76ebd6-6d6e-4635-ba8c-fca6f7b9477f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/discover/serie</value>
      <webElementGuid>fb4e72ab-b698-4a53-a2b8-934ebd59c840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white w-full group flex items-center px-4 py-2 text-sm</value>
      <webElementGuid>8e5ff836-988b-4d90-9c28-e018a36d3c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-:r7:</value>
      <webElementGuid>7ca84454-d922-473c-b739-4f5ba5b924c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>d19979d1-bf6f-4395-8058-8d4d8af75837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5930f2a1-6a80-4095-bd8e-d57f15903199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Abonnements</value>
      <webElementGuid>cb6c4e89-46e1-493d-a5bc-7487c6617abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f07d2e6371fa9a6cf33b67ce17c2ae92</value>
      <webElementGuid>b6f21f38-0e05-4ee2-b0c7-11d913db8b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/discover/serie']</value>
      <webElementGuid>ea768efa-0ad4-4903-bda6-d58782d084a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/discover/serie']</value>
      <webElementGuid>b5ea3407-d5a5-4946-97f6-0c0db749af1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/discover/serie' and @id = 'headlessui-menu-item-:r7:' and (text() = 'Abonnements' or . = 'Abonnements')]</value>
      <webElementGuid>1f4b9e19-1d40-45e0-a611-b318515d5ad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
