<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reservations</name>
   <tag></tag>
   <elementGuidId>7683b66b-17d8-410e-8534-177be75483ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Reservations')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Reservations&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>642c3810-bf68-4765-894d-5bff9b2d0bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-secondary text-accent px-4 py-1.5 rounded-[10px] shadow</value>
      <webElementGuid>04b5e7ab-1d78-43f5-898a-a9a5e7f5222a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/discover/reservation</value>
      <webElementGuid>f369c17c-e38d-46ef-b330-491109705430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservations</value>
      <webElementGuid>be72638c-e210-4777-a772-c11b1f306968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_6dfd4a __variable_f8227e notranslate&quot;]/body[1]/header[@class=&quot;fixed mb-12 
          top-0 z-[999] lg:px-4 w-full flex justify-center lg:py-4&quot;]/div[@class=&quot;relative flex items-center h-14 px-6 py-4 transition-all duration-300 max-w-[1100px] w-full justify-between gap-6 bg-primary&quot;]/div[@class=&quot;flex items-center justify-center gap-[22px]&quot;]/ul[@class=&quot;hidden lg:flex items-center gap-6 text-white/80 text-[13px] font-medium&quot;]/a[@class=&quot;bg-secondary text-accent px-4 py-1.5 rounded-[10px] shadow&quot;]</value>
      <webElementGuid>7df1d31c-ceaf-4164-824e-bcb8a5584b08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reservations')]</value>
      <webElementGuid>56fcc7d7-f0d8-40b2-a9c2-8dd3bb24cd6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contactez-nous'])[1]/following::a[1]</value>
      <webElementGuid>e60e004d-9010-4452-b10a-105605fbf5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offre'])[1]/following::a[2]</value>
      <webElementGuid>56b8ca0e-4159-4c57-94e3-74b657235267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trouvez où et avec qui jouer instantanément'])[1]/preceding::a[2]</value>
      <webElementGuid>a02726a6-58b6-4ae6-9625-6d325267d7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/preceding::a[2]</value>
      <webElementGuid>505e9caa-6f6c-47bf-a3f2-320e72f89540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reservations']/parent::*</value>
      <webElementGuid>f31acf8a-3ba5-4637-8974-4502ad6157cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/discover/reservation')]</value>
      <webElementGuid>9d2c81bb-b10d-4868-8ebd-5590fea2b651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>5ffdaf1a-ab2d-40f4-98fe-88c50b27f954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/discover/reservation' and (text() = 'Reservations' or . = 'Reservations')]</value>
      <webElementGuid>4fb3b4de-5213-4cf7-bfc1-393d1ed211cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
