<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_Rserver_Page_Home</name>
   <tag></tag>
   <elementGuidId>174b7f2b-d2b8-4127-ac92-1efc0b0782c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Réserver')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Réserver&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b63e515d-6168-44f2-a6f6-b4f283aaa22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center gap-[0.625rem] rounded-[0.625rem] h-[35px] w-[7.938rem] bg-secondary text-accent font-medium text-[1rem] text-base leading-[1.2rem] first-letter:capitalize</value>
      <webElementGuid>0145af32-de58-4199-9868-ac938c7754ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/discover/reservation</value>
      <webElementGuid>45ee6982-f8e2-408d-9d17-f776cf47cd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Réserver</value>
      <webElementGuid>00baa317-7534-41d0-8bfe-3f696d3318ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_6dfd4a __variable_f8227e notranslate&quot;]/body[1]/div[1]/main[1]/section[@class=&quot;flex items-center lg:flex-row flex-col justify-between relative sm:min-h-[700px] min-h-[600px] pt-20 sm:pb-10 pb-16 xl:px-[8.35%] lg:px-6 sm:px-4 px-1&quot;]/div[@class=&quot;flex flex-col items-start justify-between w-[100%] z-50&quot;]/div[@class=&quot;lg:block hidden&quot;]/div[@class=&quot;flex gap-4 lg:gap-8 flex-col lg:flex-row flex-wrap justify-start items-center&quot;]/a[@class=&quot;flex items-center justify-center gap-[0.625rem] rounded-[0.625rem] h-[35px] w-[7.938rem] bg-secondary text-accent font-medium text-[1rem] text-base leading-[1.2rem] first-letter:capitalize&quot;]</value>
      <webElementGuid>0b16518e-2441-4131-9584-606404c81fa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Réserver')])[2]</value>
      <webElementGuid>8f44968a-f023-46f8-bbe5-cc5520c33751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Les meilleurs terrains de la ville !! 34'])[1]/following::a[1]</value>
      <webElementGuid>7f6e702c-cfd4-443b-8c05-f2e238b3a5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Réserve ton Padel à Macon 34'])[1]/following::a[1]</value>
      <webElementGuid>d5465f28-9e21-4e66-8265-ddf97c3727d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Réserver'])[2]/preceding::a[1]</value>
      <webElementGuid>7a755394-a775-4816-88c2-2b17fbe058d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VR Game'])[1]/preceding::a[2]</value>
      <webElementGuid>e2146d2a-5f22-44e5-9f77-144fec56212b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Réserver']/parent::*</value>
      <webElementGuid>f4a61b86-247c-4086-9073-4023f0911b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/discover/reservation')])[2]</value>
      <webElementGuid>3197e12f-439b-41f0-8bb0-9df2ac9edaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>12742e1c-72a7-4bce-9e07-767699d3f484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/discover/reservation' and (text() = 'Réserver' or . = 'Réserver')]</value>
      <webElementGuid>9156b8c1-146e-40a0-b22f-2ac49e4ac168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
