<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accepter</name>
   <tag></tag>
   <elementGuidId>65ecd9ef-a721-4f1d-abb9-bda1708a1acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='En savoir plus.'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.c15t-button-YKOgW.c15t-button-small-n5LJg.c15t-button-primary-stroke-TWzjH</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;cookie-banner-footer-sub-group&quot;] [data-testid=&quot;cookie-banner-accept-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4a3a169-459c-4835-8b96-d49b383400b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c15t-button-YKOgW c15t-button-small-n5LJg c15t-button-primary-stroke-TWzjH</value>
      <webElementGuid>3ec27989-e9db-42e7-954f-98672878d8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cookie-banner-accept-button</value>
      <webElementGuid>ee1b17a2-c3cf-454c-b61c-ed574ac3a5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepter</value>
      <webElementGuid>92bb3206-14a9-43dd-8dda-1345ec95eda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_6dfd4a __variable_f8227e notranslate&quot;]/body[1]/div[@class=&quot;c15t-root-tnx7V c15t-bottomLeft-wv7ez c15t-bannerVisible-bty7Y&quot;]/div[@class=&quot;c15t-card-MOqQY&quot;]/div[@class=&quot;banner-header banner-header banner-header c15t-header-X6bpE&quot;]/div[@class=&quot;desktop-footer desktop-footer desktop-footer c15t-footer-wS150&quot;]/div[@class=&quot;c15t-footerSubGroup-HbTp3&quot;]/button[@class=&quot;c15t-button-YKOgW c15t-button-small-n5LJg c15t-button-primary-stroke-TWzjH&quot;]</value>
      <webElementGuid>7f11d139-48cb-4cbd-b9d3-16b34f9aaa03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En savoir plus.'])[1]/following::button[1]</value>
      <webElementGuid>f52d6969-8898-45bb-9358-43f0811a07de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refuser'])[1]/preceding::button[1]</value>
      <webElementGuid>f878c0fd-5754-4777-8ef5-cbdb04ec4290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Préférences'])[1]/preceding::button[2]</value>
      <webElementGuid>00905c81-cf15-43c6-9b1c-a59d9f08c2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accepter']/parent::*</value>
      <webElementGuid>83cf1ba2-595b-4f4e-b3b4-125c027bc6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>eee8f139-11a9-4cd6-8fee-55dff99480da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Accepter' or . = 'Accepter')]</value>
      <webElementGuid>25544f63-a74f-442f-9939-659c1e3f4c90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
