<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Refuser</name>
   <tag></tag>
   <elementGuidId>c813674c-c34e-4d29-9e6a-b3716dc08769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.c15t-button-YKOgW.c15t-button-small-n5LJg.c15t-button-neutral-stroke-EAzCC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@class='c15t-button-YKOgW c15t-button-small-n5LJg c15t-button-neutral-stroke-EAzCC'][normalize-space()='Refuser'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;cookie-banner-footer-sub-group&quot;] [data-testid=&quot;cookie-banner-reject-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b57e0871-c6e8-431b-9d95-b941e79d7ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c15t-button-YKOgW c15t-button-small-n5LJg c15t-button-neutral-stroke-EAzCC</value>
      <webElementGuid>73204f28-ecba-4319-a7bf-6e58c1d7c8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cookie-banner-reject-button</value>
      <webElementGuid>3959c79c-cda4-4669-9c1b-be230f736fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refuser</value>
      <webElementGuid>3b53162d-c9a5-42f4-8679-ecfc432cbef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_6dfd4a __variable_f8227e notranslate&quot;]/body[1]/div[@class=&quot;c15t-root-tnx7V c15t-bottomLeft-wv7ez c15t-bannerVisible-bty7Y&quot;]/div[@class=&quot;c15t-card-MOqQY&quot;]/div[@class=&quot;banner-header banner-header banner-header c15t-header-X6bpE&quot;]/div[@class=&quot;desktop-footer desktop-footer desktop-footer c15t-footer-wS150&quot;]/div[@class=&quot;c15t-footerSubGroup-HbTp3&quot;]/button[@class=&quot;c15t-button-YKOgW c15t-button-small-n5LJg c15t-button-neutral-stroke-EAzCC&quot;]</value>
      <webElementGuid>a2c7b4d5-e890-44d2-9d51-807ce0ba8d97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accepter'])[1]/following::button[1]</value>
      <webElementGuid>a1a1b16c-c327-451f-95d5-a9c72444d804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En savoir plus.'])[1]/following::button[2]</value>
      <webElementGuid>92d5578f-a26e-46e5-97fb-b581c0211492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Préférences'])[1]/preceding::button[1]</value>
      <webElementGuid>7fe3926a-a03b-49d8-9ba9-7b0fc8e506a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accepter'])[2]/preceding::button[2]</value>
      <webElementGuid>6fe46407-be93-46e6-98a2-aa5dfe4b3b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refuser']/parent::*</value>
      <webElementGuid>930ce59c-80f2-41fa-8b1f-4a6146060c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>6cafa579-4b4c-4f7f-bf65-e67e51123cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Refuser' or . = 'Refuser')]</value>
      <webElementGuid>51ebcc11-eed4-4c6f-a311-ef5f36d52836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
