<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accepter</name>
   <tag></tag>
   <elementGuidId>65ecd9ef-a721-4f1d-abb9-bda1708a1acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.c15t-button-YKOgW.c15t-button-small-n5LJg.c15t-button-primary-stroke-TWzjH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@class='c15t-button-YKOgW c15t-button-small-n5LJg c15t-button-primary-stroke-TWzjH'][normalize-space()='Accepter'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;cookie-banner-footer-sub-group&quot;] [data-testid=&quot;cookie-banner-accept-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4b28514-1031-4261-9790-8630f81d6187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c15t-button-YKOgW c15t-button-small-n5LJg c15t-button-primary-stroke-TWzjH</value>
      <webElementGuid>1cc4eafd-f3c5-47b9-a0c3-a71b54e22ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cookie-banner-accept-button</value>
      <webElementGuid>49e03528-a1fb-4c26-91e4-65414e5fd9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepter</value>
      <webElementGuid>5ce441dd-2f71-4090-863c-d7283b040488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;__variable_6dfd4a __variable_f8227e notranslate&quot;]/body[1]/div[@class=&quot;c15t-root-tnx7V c15t-bottomLeft-wv7ez c15t-bannerVisible-bty7Y&quot;]/div[@class=&quot;c15t-card-MOqQY&quot;]/div[@class=&quot;banner-header banner-header banner-header c15t-header-X6bpE&quot;]/div[@class=&quot;desktop-footer desktop-footer desktop-footer c15t-footer-wS150&quot;]/div[@class=&quot;c15t-footerSubGroup-HbTp3&quot;]/button[@class=&quot;c15t-button-YKOgW c15t-button-small-n5LJg c15t-button-primary-stroke-TWzjH&quot;]</value>
      <webElementGuid>1283ce1b-6b25-4243-a746-533cf5d6cf95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En savoir plus.'])[1]/following::button[1]</value>
      <webElementGuid>697d3204-cad8-4917-8fa4-5cb465ac1104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refuser'])[1]/preceding::button[1]</value>
      <webElementGuid>85419e4a-134c-4ad1-baba-855330a47fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Préférences'])[1]/preceding::button[2]</value>
      <webElementGuid>262cedeb-4968-43dc-8df0-ccc92592d07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accepter']/parent::*</value>
      <webElementGuid>c539af37-3cff-4454-9b8a-30d31ebe6efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>052005ac-9275-468d-900a-cd3acb8d2bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Accepter' or . = 'Accepter')]</value>
      <webElementGuid>ec66140c-fec3-46b0-a5a4-c3791350b3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
