<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_xxxxxxxxxxxx42421126</name>
   <tag></tag>
   <elementGuidId>f098b2a5-8489-4d9e-b854-37387317b4ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@class='relative rounded-lg w-[17px] h-[17px] border-2 bg-white'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;headlessui-radiogroup-option-\:r1p\:&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3184a5a2-4bf9-4bf8-86bc-fd40a875e640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
                cursor-pointer rounded-lg lg:px-5 px-4 py-4 my-3 shadow-md focus:outline-none overflow-hidden overflow-ellipsis</value>
      <webElementGuid>e4e6a90a-63ba-4342-a59f-ef6486d2ac23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-radiogroup-option-:r1p:</value>
      <webElementGuid>e2f24af5-5201-4117-bd93-cd23f9a34544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>074252d3-0355-41ce-9b3c-b2c1a3a6f39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bbe9a2ad-2af3-408f-a597-53f5a7d3f8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f54510a6-f716-4fb6-aa42-1e050d94ae34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>7c0e102a-156e-4e98-b641-f9766f599174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>xxxxxxxxxxxx424211/26</value>
      <webElementGuid>8856e7ba-8e40-4ea1-8a5a-ddeb1e390503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-radiogroup-option-:r1p:&quot;)</value>
      <webElementGuid>f0b7d85d-27a7-4dca-af04-02e518d876ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='headlessui-radiogroup-option-:r1p:']</value>
      <webElementGuid>a3c2cc2b-0b42-4e77-a75e-2fc5c615ac19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-radiogroup-:r1o:']/div</value>
      <webElementGuid>fe9f7043-a75f-44bb-9030-b0a62ad73a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moyen de paiement'])[1]/following::div[12]</value>
      <webElementGuid>4e5f32ec-819c-4c85-a42a-65822a94fde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='xxxxxxxxxxxx4242'])[2]/preceding::div[3]</value>
      <webElementGuid>4991c6e2-b452-40cd-b4e3-64c9a3ba1ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>244e9f80-c34c-4443-b48c-0d940d382327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'headlessui-radiogroup-option-:r1p:' and (text() = 'xxxxxxxxxxxx424211/26' or . = 'xxxxxxxxxxxx424211/26')]</value>
      <webElementGuid>67b1ad8c-a2a2-4649-a588-eceabb940e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
