<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Connectez-vous</name>
   <tag></tag>
   <elementGuidId>f2f0b481-b71a-4f7b-b5f8-8399585edd96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.poppinsSemiBold.mb-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Connectez-vous&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b4b5add6-ca75-4b1b-8765-ee518a17c4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poppinsSemiBold mb-4</value>
      <webElementGuid>bc6a02f3-163a-4072-b8b9-4bd107d390c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connectez-vous</value>
      <webElementGuid>971b5e63-d79c-4b07-824b-fb7325b9d694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/h2[@class=&quot;poppinsSemiBold mb-4&quot;]</value>
      <webElementGuid>f68f3e6c-17df-4893-b63d-3462b67be117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/h2</value>
      <webElementGuid>edfc3545-ead2-441e-b82f-7ae9eab521b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to PlayPro.'])[1]/following::h2[1]</value>
      <webElementGuid>82470180-38cc-4fd2-839c-b85376a46948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connexion'])[1]/preceding::h2[1]</value>
      <webElementGuid>49e84fd4-5328-48ae-8766-4703eb4646fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Connectez-vous']/parent::*</value>
      <webElementGuid>ff0b2847-d21f-4b3c-b393-e2dec316a702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>61ae3585-7366-479b-b24d-c4c9c21dd3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Connectez-vous' or . = 'Connectez-vous')]</value>
      <webElementGuid>fcd16ad1-2da8-4d08-b6fb-cfdbcb71cc31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
